# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader: false
    body_listener: true
    view:
        view_response_listener:  true
    serializer:
        serialize_null: true
    exception:
        serialize_exceptions: false
        exception_listener: false
        enabled: true
        messages:
            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
