monolog:
    channels: ['mailer', 'filer', 'retriever', 'file_processing','doi_issue', 'create_homedir', 'virus_scan', 'delete_file', 'zipper', 'rename_file']

    handlers:
        mailer:
            level:    debug
            type:     stream
            path:     "%kernel.logs_dir%/mailer.log"
            channels: [mailer]

        filer:
            type: stream
            path: "%kernel.logs_dir%/filer.log"
            level: info
            channels: [filer]

        retriever:
            type: stream
            path: "%kernel.logs_dir%/retriever.log"
            level: info
            channels: [retriever]

        file_processing:
            type: stream
            path: "%kernel.logs_dir%/file_processing.log"
            level: info
            channels: [file_processing]

        doi_issue:
            type: stream
            path: "%kernel.logs_dir%/doi_issue.log"
            level: info
            channels: [doi_issue]

        create_homedir:
            type: stream
            path: "%kernel.logs_dir%/create_homedir.log"
            level: info
            channels: [create_homedir]

        virus_scan:
            type: stream
            path: "%kernel.logs_dir%/virus_scan.log"
            level: info
            channels: [virus_scan]

        delete_file:
            type: stream
            path: "%kernel.logs_dir%/delete_file.log"
            level: info
            channels: [ delete_file ]

        zipper:
            type: stream
            path: "%kernel.logs_dir%/zipper.log"
            level: info
            channels: [ zipper ]

        rename_file:
            type: stream
            path: "%kernel.logs_dir%/rename_file.log"
            level: info
            channels: [ rename_file ]
