old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        create_homedir:
            connection:       default
            exchange_options: { name: 'create_homedir', type: direct }
        doi_issue:
            connection:       default
            exchange_options: { name: 'doi_issue', type: topic }
    consumers:
        create_homedir:
            connection:       default
            exchange_options: { name: 'create_homedir', type: direct }
            callback:         App\Consumer\CreateHomedirConsumer
            queue_options:
                name: 'create_homedir'
        doi_issue:
            connection:       default
            exchange_options: { name: 'doi_issue', type: topic }
            callback:         App\Consumer\DoiConsumer
            qos_options:      { prefetch_count: 1, global: false }
            queue_options:
                name: 'doi_issue'
                routing_keys:
                    - 'doi'
                    - 'delete'
