# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        upload_file_adapter:
            local:
                directory: '%env(HOMEDIR_PREFIX)%'
        data_store_adapter:
            local:
                directory: '%env(DATA_STORE_DIRECTORY)%'
    filesystems:
        upload_flysystem:
            adapter: upload_file_adapter
        datastore_flysystem:
            adapter: data_store_adapter
