language: php

dist: trusty
sudo: false

git:
    depth: 1

env:
    global:
        - MIN_PHP=7.1.3

matrix:
    include:
        - php: 7.1
        - php: 5.6
        - php: 7.2

    fast_finish: true

cache:
    directories:
        - .phpunit

services:
    - rabbitmq
