_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /%pelagos.prefix%/_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /%pelagos.prefix%/_profiler

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /%pelagos.prefix%/_error

_main:
    resource: routing.yml
    prefix:   /%pelagos.prefix%
