security:

    providers:
        pelagos_account:
            entity:
                class: Pelagos:Account
                property: userId
        person_token:
            id: person_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        account:
            pattern: ^/ui/Account
            stateless: true
            # allow anonymous access
            anonymous: ~
            # use REMOTE_USER environment variable if set
            remote_user:
                provider: pelagos_account
            # use a Person Token, if present
            simple_preauth:
                authenticator: person_token_authenticator
                provider: person_token

        main:
            # allow anonymous access
            anonymous: ~
            # use REMOTE_USER environment variable if set
            remote_user:
                provider: pelagos_account

services:
    super_user_voter:
        class: Pelagos\Bundle\AppBundle\Security\SuperUserVoter
        tags:
            - { name: security.voter }
    research_group_voter:
        class: Pelagos\Bundle\AppBundle\Security\ResearchGroupVoter
        tags:
            - { name: security.voter }
    person_research_group_voter:
        class: Pelagos\Bundle\AppBundle\Security\PersonResearchGroupVoter
        tags:
            - { name: security.voter }
    person_voter:
        class: Pelagos\Bundle\AppBundle\Security\PersonVoter
        tags:
            - { name: security.voter }
    person_token_voter:
        class: Pelagos\Bundle\AppBundle\Security\PersonTokenVoter
        tags:
            - { name: security.voter }
    account_voter:
        class: Pelagos\Bundle\AppBundle\Security\AccountVoter
        tags:
            - { name: security.voter }

