# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    postgres_session_init.listener:
        class: Pelagos\DoctrineExtensions\DBAL\Event\Listeners\PostgresSessionInit
        arguments:
            - { timezone: UTC, intervalstyle: iso_8601 }
        tags:
            - { name: doctrine.event_listener, event: postConnect }

    person_token_user_provider:
        class: Pelagos\Bundle\AppBundle\Security\PersonTokenUserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    person_token_authenticator:
        class: Pelagos\Bundle\AppBundle\Security\PersonTokenAuthenticator
        arguments: ["@twig"]
        public: false

    pelagos.ldap_client:
        class: Pelagos\Component\Ldap\LdapClient
        arguments: ["%ldap_host%"]

    pelagos.ldap:
        class: Pelagos\Component\Ldap\Ldap
        arguments: ["@pelagos.ldap_client","%ldap_bind_dn%","%ldap_bind_pw%","%ldap_people_ou%"]

    pelagos.util.udi:
        class: Pelagos\Util\Udi
        arguments: ["@doctrine.orm.entity_manager"]

    pelagos.util.data_store:
        class: Pelagos\Util\DataStore
        arguments: ["%data_store_directory%","%data_download_directory%"]

    pelagos.event.entity_event_dispatcher:
        class: Pelagos\Event\EntityEventDispatcher
        arguments: ["@event_dispatcher"]

    monolog.processor.process_id:
        class: Monolog\Processor\ProcessIdProcessor
        tags:
            - { name: monolog.processor, channel: filer }
            - { name: monolog.processor, channel: retriever }

    pelagos.console.listener:
        class: Pelagos\Event\ConsoleListener
        tags:
            - { name: kernel.event_listener, event: console.exception, method: onException }
