# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['fightingtexasaggie@gmail.com']
    disable_delivery: false
