# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['michael.vandeneijnden@tamucc.edu']
    #disable_delivery: true
