framework:
    messenger:
        routing:
            'App\Message\DatasetSubmissionFilerHandler': async
            'App\Message\DeleteFileHandler': async
            'App\Message\HashFile': async
            'App\Message\ScanFileForVirus': async
