framework:
    messenger:
        routing:
            'App\Message\DatasetSubmissionFiler': async
            'App\Message\DeleteFile': async
            'App\Message\HashFile': async
            'App\Message\ScanFileForVirus': async
