framework:
    messenger:
        routing:
            'App\Message\DatasetSubmissionFiler': async
            'App\Message\DeleteFile': async
            'App\Message\ProcessFile': async
            'App\Message\ScanFileForVirus': async
            'App\Message\ZipDatasetFiles': async
            'App\Message\RenameFile': async
