framework:
    messenger:
        failure_transport: failed

        transports:
            async_normal: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'
            async_slow: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=slow'
            async_doi: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=doi'

        routing:
            # Slow running Handlers
            'App\Message\DatasetSubmissionFiler': async_slow
            'App\Message\ScanFileForVirus': async_slow
            'App\Message\ZipDatasetFiles': async_slow
            # Normal Handlers
            'App\Message\RenameFile': async_normal
            'App\Message\DeleteFile': async_normal
            'App\Message\ProcessFile': async_normal
            'App\Message\DeleteDir': async_normal
            # DOI Handler
            'App\Message\DoiMessage': async
