monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]

        filer:
            type: stream
            path: "%kernel.project_dir%/var/logs/filer.log"
            level: info
            channels: [filer]

        retriever:
            type: stream
            path: "%kernel.project_dir%/var/logs/retriever.log"
            level: info
            channels: [retriever]

        dataset_file_hasher:
            type: stream
            path: "%kernel.project_dir%/var/logs/dataset_file_hasher.log"
            level: info
            channels: [dataset_file_hasher]

        doi_issue:
            type: stream
            path: "%kernel.project_dir%/var/logs/doi_issue.log"
            level: info
            channels: [doi_issue]

        create_homedir:
            type: stream
            path: "%kernel.project_dir%/var/logs/create_homedir.log"
            level: info
            channels: [create_homedir]