funding_organizations:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\FundingOrganizationController
    name_prefix: funding_organizations_
    prefix: funding_organizations

funding_cycles:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\FundingCycleController
    name_prefix: funding_cycles_
    prefix: funding_cycles

research_groups:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\ResearchGroupController
    name_prefix: research_groups_
    prefix: research_groups

person_research_groups:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\PersonResearchGroupController
    name_prefix: person_research_groups_
    prefix: person_research_groups

person_data_repositories:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\PersonDataRepositoryController
    name_prefix: person_data_repositories_
    prefix: person_data_repositories

people:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\PersonController
    name_prefix: people_
    prefix: people
