pelagos_data_repository_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DataRepositoryController

pelagos_funding_cycle_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\FundingCycleController

pelagos_funding_organization_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\FundingOrganizationController

pelagos_person_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonController

pelagos_person_funding_organization_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonFundingOrganizationController

pelagos_person_research_group_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonResearchGroupController

pelagos_research_group_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\ResearchGroupController

pelagos_person_data_repository_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PersonDataRepositoryController

pelagos_account_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\AccountController

pelagos_dif_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DIFController

pelagos_dataset_submission_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetSubmissionController

pelagos_datset_monitoring_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetMonitoringController

pelagos_dataset_summary_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatasetSummaryController

pelagos_publication_dataset_link_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\PublicationDatasetLinkController

pelagos_dataland_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DatalandController

pelagos_stats_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\StatsController

pelagos_doi_request_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DoiRequestController

pelagos_mdapp_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\MdAppController

pelagos_data_discovery_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DataDiscoveryController

pelagos_gomri_reports_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\GomriReportController

pelagos_download_report_ui:
    resource: Pelagos\Bundle\AppBundle\Controller\UI\DownloadReportController