pelagos_app_homepage:
    path:     /
    defaults: { _controller: PelagosAppBundle:Default:index }
    
pelagos_ui:
    path:     /ui/{template}/{id}
    defaults: { _controller: PelagosAppBundle:UI:index, id: null }

pelagos_rest:
    type: rest
    resource: "@PelagosAppBundle/Resources/config/routing_rest.yml"

NelmioApiDocBundle:
    prefix:   /api/doc
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
