pelagos_app_homepage:
    path:     /
    defaults: { _controller: PelagosAppBundle:Default:index }

pelagos_ui:
    prefix: ui
    resource: "@PelagosAppBundle/Resources/config/routing_ui.yml"

pelagos_list:
    prefix: lists
    resource: Pelagos\Bundle\AppBundle\Controller\ListController

pelagos_rest:
    type: rest
    resource: "@PelagosAppBundle/Resources/config/routing_rest.yml"

NelmioApiDocBundle:
    prefix:   /api/doc
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
