pelagos_homepage:
    path:     /
    defaults: { _controller: PelagosAppBundle:Default:index }

pelagos_admin:
    path:     /admin
    defaults: { _controller: PelagosAppBundle:Default:admin }
    
pelagos_sitemap:
    path:     /sitemap.xml
    defaults: { _controller: PelagosAppBundle:Default:showSiteMapXml }

pelagos_ui:
    resource: "@PelagosAppBundle/Resources/config/routing_ui.yml"

pelagos_list:
    resource: Pelagos\Bundle\AppBundle\Controller\ListController

pelagos_rest:
    type: rest
    resource: "@PelagosAppBundle/Resources/config/routing_rest.yml"

NelmioApiDocBundle:
    prefix:   /api/doc
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"

pelagos_download:
    resource: Pelagos\Bundle\AppBundle\Controller\DownloadController

pelagos_gml:
    resource: Pelagos\Bundle\AppBundle\Controller\GmlController

pelagos_geoviz:
    resource: "@PelagosAppBundle/Resources/config/routing_geoviz.yml"

pelagos_metadata:
    path:     /metadata/{udi}
    defaults: { _controller: PelagosAppBundle:UI/Dataland:metadata }
