funding_cycles:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\FundingCycleController
    name_prefix: funding_cycles_
    prefix: funding_cycles

research_groups:
    type: rest
    resource: Pelagos\Bundle\AppBundle\Controller\Api\ResearchGroupController
    name_prefix: research_groups_
    prefix: research_groups
