services:
    pelagos.entity.handler:
        class: Pelagos\Bundle\AppBundle\Handler\EntityHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker"]

    pelagos.twig.extensions:
        class: Pelagos\Bundle\AppBundle\Twig\Extensions
        public: false
        tags:
            - { name: twig.extension }

    pelagos.twig_entity_extensions:
        class: Pelagos\TwigEntityExtensions
        public: false
        tags:
            - { name: twig.extension }

    pelagos.form.type.person:
        class: Pelagos\Bundle\AppBundle\Form\PersonType
        arguments: ["@router"]
        tags:
            - { name: form.type }
    pelagos.dif.listener:
        class: Pelagos\Event\DIFListener
        arguments: ["@twig", "@mailer"]
        tags:
            - { name: kernel.event_listener, event: dif.submitted, method: onSubmitted }
            - { name: kernel.event_listener, event: dif.approved, method: onApproved }
            - { name: kernel.event_listener, event: dif.rejected, method: onRejected }
            - { name: kernel.event_listener, event: dif.unlocked, method: onUnlocked }
