services:
    pelagos.entity.handler:
        class: Pelagos\Bundle\AppBundle\Handler\EntityHandler
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker", "@event_dispatcher"]

    pelagos.twig.extensions:
        class: Pelagos\Bundle\AppBundle\Twig\Extensions
        public: false
        tags:
            - { name: twig.extension }

    pelagos.twig_entity_extensions:
        class: Pelagos\TwigEntityExtensions
        public: false
        tags:
            - { name: twig.extension }

    pelagos.form.type.person:
        class: Pelagos\Bundle\AppBundle\Form\PersonType
        arguments: ["@router"]
        tags:
            - { name: form.type }

    pelagos.dif.listener:
        class: Pelagos\Event\DIFListener
        arguments: ["@twig", "@mailer", "@security.token_storage", "%mailer_from_addr%", "%mailer_from_name%"]
        tags:
            - { name: kernel.event_listener, event: pelagos.entity.dif.dataset_created, method: onCreated }
            - { name: kernel.event_listener, event: pelagos.entity.dif.submitted, method: onSubmitted }
            - { name: kernel.event_listener, event: pelagos.entity.dif.approved, method: onApproved }
            - { name: kernel.event_listener, event: pelagos.entity.dif.unlock_requested, method: onUnlockRequested }
            - { name: kernel.event_listener, event: pelagos.entity.dif.unlocked, method: onUnlocked }

    pelagos.form.type.dif:
        class: Pelagos\Bundle\AppBundle\Form\DIFType
        arguments: ["@doctrine.orm.entity_manager", "@security.authorization_checker"]
        tags:
            - { name: form.type }

    pelagos.rabbit.consumer.filer:
        class: Pelagos\Bundle\AppBundle\Rabbit\Consumer\FilerConsumer
        arguments: ["@doctrine.orm.entity_manager", "@pelagos.util.data_store", "@logger"]
        tags:
            - { name: monolog.logger, channel: filer }
