pelagos_legacy_static:
    path:     /static/{file}
    defaults: { _controller: PelagosLegacyBundle:Default:static }
    requirements:
        file: .+

pelagos_legacy_comp_static:
    path:     /{category}/{target}/static/{file}
    defaults: { _controller: PelagosLegacyBundle:Default:static }
    requirements:
        file: .+

pelagos_legacy_exec:
    path:     /{category}/{target}/{route}
    defaults: { _controller: PelagosLegacyBundle:Default:exec, route: "" }
    requirements:
        route: .*
