name: ESLint for Javascript

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Install node modules
      run: yarn

    - name: Run ESLint
      run: yarn run eslint ./assets/js/
